### ISSUE TITLE
When stats if off than turbo management not working

### ISSUE THREAD

**Issue by treepoint** [treepoint/AveTemp#10]
Traceback (most recent call last):
  File "D:\Nextcloud\Code\avetemp\Avetemp.py", line 108, in <module>
    app = TrayWrapper()
  File "D:\Nextcloud\Code\avetemp\Avetemp.py", line 38, in __init__
    self.window = MainWindow.Main()
  File "D:\Nextcloud\Code\avetemp\MainWindow.py", line 127, in __init__
    CPU_performance_mode = hardware.setCpuPerformanceState(self.config, self.data_lists)
  File "D:\Nextcloud\Code\avetemp\hardware.py", line 158, in setCpuPerformanceState
    if int(data[0]) > int(config.getCPUThreshhold()):
IndexError: list index out of range

**Comment by treepoint** [comment]
https://github.com/treepoint/AveTemp/commit/307bfa58a3cbba6a13b192c9bb675bd272a9674d
