### ISSUE TITLE
CPU load sometimes not updates after windows sleep

### ISSUE THREAD

**Issue by treepoint** [treepoint/AveTemp#47]
Traceback (most recent call last):
  File "logger.py", line 21, in output_func
  File "MainWindow.py", line 38, in main
Exception: AveTemp is already running
Traceback (most recent call last):
  File "logger.py", line 21, in output_func
  File "AveTemp.py", line 70, in main
AttributeError: 'Main' object has no attribute 'image'
Traceback (most recent call last):
  File "logger.py", line 21, in output_func
  File "hardware.py", line 98, in collectFastData
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.

Parameter name: index

   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)

   at System.Collections.Generic.List`1.RemoveAt(Int32 index)

   at LibreHardwareMonitor.Hardware.Sensor.set_Value(Nullable`1 value)

   at LibreHardwareMonitor.Hardware.CPU.GenericCpu.Update()

   at LibreHardwareMonitor.Hardware.CPU.Amd17Cpu.Update()
Traceback (most recent call last):
  File "logger.py", line 21, in output_func
  File "workers.py", line 119, in run
TypeError: CollectFastDataWorker.result[dict].emit(): argument 1 has unexpected type 'NoneType'

**Comment by treepoint** [comment]
Will be fixed here — https://github.com/treepoint/AveTemp/tree/1.4.6_version
